spring:
  #jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_management?serverTimezone=UTC
    username: root
    password: miu123cB@
  jpa:
    generate-ddl: true