spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_management
    username: root
    password: quocnamle
  jpa:
    generate-ddl: true
    show-sql: true
  #    properties:
  #      hibernate:
  #        format-sql: true

  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false

  # Static resources reloading during development
  resources:
    static-locations: file:src/main/resources/static/
#    cache-period: 0
